/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-03-23 12:38:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userregister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>User Registration</title>\n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("	font-family: 'Verdana', sans-serif;\n");
      out.write("	background-color: #e6e6e6;\n");
      out.write("	margin: 0;\n");
      out.write("	padding: 0;\n");
      out.write("	justify-content: center;\n");
      out.write("	align-items: center;\n");
      out.write("	height: 100vh;\n");
      out.write("}\n");
      out.write("\n");
      out.write("h2 {\n");
      out.write("	text-align: center;\n");
      out.write("	color: #444;\n");
      out.write("	text-transform: uppercase;\n");
      out.write("}\n");
      out.write("\n");
      out.write("form {\n");
      out.write("	background-color: #fff;\n");
      out.write("	padding: 40px;\n");
      out.write("	border-radius: 8px;\n");
      out.write("	box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);\n");
      out.write("	width: 400px;\n");
      out.write("	max-width: 100%;\n");
      out.write("	box-sizing: border-box;\n");
      out.write("	margin: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("label {\n");
      out.write("	display: block;\n");
      out.write("	margin-bottom: 15px;\n");
      out.write("	color: #555;\n");
      out.write("	font-size: 14px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input {\n");
      out.write("	width: 100%;\n");
      out.write("	padding: 15px;\n");
      out.write("	margin-bottom: 25px;\n");
      out.write("	box-sizing: border-box;\n");
      out.write("	border: 2px solid #ddd;\n");
      out.write("	border-radius: 6px;\n");
      out.write("	font-size: 16px;\n");
      out.write("	transition: border-color 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input:focus {\n");
      out.write("	border-color: #6b5b95;\n");
      out.write("}\n");
      out.write("\n");
      out.write("button {\n");
      out.write("	background-color: #6b5b95;\n");
      out.write("	color: #fff;\n");
      out.write("	padding: 15px 25px;\n");
      out.write("	border: none;\n");
      out.write("	border-radius: 6px;\n");
      out.write("	cursor: pointer;\n");
      out.write("	font-size: 16px;\n");
      out.write("	transition: background-color 0.3s ease;\n");
      out.write("	display: block;\n");
      out.write("	margin: 0 auto; /* Center the button */\n");
      out.write("}\n");
      out.write("\n");
      out.write("button:hover {\n");
      out.write("	background-color: #4a3b6a;\n");
      out.write("}\n");
      out.write("\n");
      out.write("p {\n");
      out.write("	text-align: center;\n");
      out.write("	margin-top: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("p a {\n");
      out.write("	color: #3498db;\n");
      out.write("	text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("p a:hover {\n");
      out.write("	text-decoration: underline;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<h2>User Registration Form</h2>\n");
      out.write("	<form action=\"register\" method=\"post\">\n");
      out.write("		<label for=\"username\">Username:</label> <input type=\"text\"\n");
      out.write("			id=\"username\" name=\"username\" required> <label for=\"email\">Email:</label>\n");
      out.write("		<input type=\"email\" id=\"email\" name=\"email\" required> <label\n");
      out.write("			for=\"password\">Password:</label> <input type=\"password\" id=\"password\"\n");
      out.write("			name=\"password\" required> \n");
      out.write("		\n");
      out.write("\n");
      out.write("		<button type=\"submit\">Register</button>\n");
      out.write("		<p>\n");
      out.write("			or you can <a\n");
      out.write("				href=\"http://localhost:8080/Student-Register-work/login\">Login</a>\n");
      out.write("		</p>\n");
      out.write("	</form>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
